/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PCard: typeof import('primevue/card')['default']
    PColumn: typeof import('primevue/column')['default']
    PDataTable: typeof import('primevue/datatable')['default']
    PDataView: typeof import('primevue/dataview')['default']
    PFluid: typeof import('primevue/fluid')['default']
    PGalleria: typeof import('primevue/galleria')['default']
    PIftaLabel: typeof import('primevue/iftalabel')['default']
    PInputGroup: typeof import('primevue/inputgroup')['default']
    PInputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    PInputNumber: typeof import('primevue/inputnumber')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PMenubar: typeof import('primevue/menubar')['default']
    PMessage: typeof import('primevue/message')['default']
    PPaginator: typeof import('primevue/paginator')['default']
    PPanel: typeof import('primevue/panel')['default']
    PPopover: typeof import('primevue/popover')['default']
    PProgressSpinner: typeof import('primevue/progressspinner')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PSkeleton: typeof import('primevue/skeleton')['default']
    PStep: typeof import('primevue/step')['default']
    PStepList: typeof import('primevue/steplist')['default']
    PStepper: typeof import('primevue/stepper')['default']
    PTag: typeof import('primevue/tag')['default']
    PTimeline: typeof import('primevue/timeline')['default']
    PToast: typeof import('primevue/toast')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
